### ISSUE TITLE
Multiple Packages in project

### ISSUE THREAD

**Issue by considerate** [nix-community/poetry2nix#1098]
### Describe the issue

Does `poetry2nix` have support for building projects with [multiple packages](https://python-poetry.org/docs/pyproject/#packages)? 

I have tried to use `mkPoetryPackages` but it doesn't seem to register packages for the local packages (listed below as `package-a` and `package-b`).

Ideally I'd like a way where I can get a separate derivation to build for each of the local packages and run tests for the individual packages in isolation.

### Additional context

`pyproject.toml`:
```toml
[tool.poetry]
name = "example-package"
version = "0.1.0"
description = ""
authors = []
packages = [
  {include = "package-a", from = "lib"},
  {include = "package-b", from = "lib"}
]

[tool.poetry.dependencies]

[tool.poetry.group.dev.dependencies]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

```
