### ISSUE TITLE
passing poetry config

### ISSUE THREAD

**Issue by akcheung** [nix-community/poetry2nix#1171]
### Describe the issue
I am trying to use `poetry2nix.mkPoetryEnv` to set up a poetry environment but I have custom poetry `no-binary` config stored in a separate `poetry.toml` file. How can I pass that that file's contents to `mkPoetryEnv` in addition to my `pyproject.toml` and `poetry.lock`?

**Comment by MoritzBoehme** [comment]
I have a somewhat similar problem, in that I have my credentials to a private package index stored in the `poetry.toml` file like so:
```toml
[http-basic.my_index]
username = "******"
password = "******"
```
