### ISSUE TITLE
Unable to use Google's `protobuf` library

### ISSUE THREAD

**Issue by mirkolenz** [nix-community/poetry2nix#1175]
### Describe the issue

I am currently investigating packaging some of my Python packages with poetry2nix. In the process, I faced the issue that it is not possible to use Google's protobuf library.

When running

`nix build github:recap-utr/arguebuf-python/beta && ./result/bin/arguebuf --help`

I get the following error:

`ModuleNotFoundError: No module named 'google.protobuf'`

### Additional context

The source code is available here: [`arguebuf-python`](https://github.com/recap-utr/arguebuf-python/tree/beta). The `protobuf` and `grpcio` libraries are included via the dependency [`arg-services`](https://github.com/recap-utr/arg-services-python).

`flake.nix`:
```nix
{
  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixpkgs-unstable";
    flake-parts.url = "github:hercules-ci/flake-parts";
    systems.url = "github:nix-systems/default";
    poetry2nix = {
      url = "github:nix-community/poetry2nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };
  outputs = inputs @ {
    flake-parts,
    nixpkgs,
    poetry2nix,
    systems,
    ...
  }:
    flake-parts.lib.mkFlake {inherit inputs;} {
      systems = import systems;
      perSystem = {
        pkgs,
        lib,
        system,
        self',
        ...
      }: let
        python = pkgs.python311;
        poetry = pkgs.poetry;
      in {
        packages = let
          inherit (poetry2nix.legacyPackages.${system}) mkPoetryApplication;
          app = mkPoetryApplication {
            inherit python;
            projectDir = ./.;
            preferWheels = true;
          };
        in {
          arguebuf = app;
          default = app;
          releaseEnv = pkgs.buildEnv {
            name = "release-env";
            paths = [poetry python];
          };
        };
        devShells.default = pkgs.mkShell {
          packages = [poetry python];
          propagatedBuildInputs = with pkgs; [graphviz d2];
          POETRY_VIRTUALENVS_IN_PROJECT = true;
          LD_LIBRARY_PATH = lib.makeLibraryPath [pkgs.stdenv.cc.cc];
          shellHook = ''
            ${lib.getExe poetry} env use ${lib.getExe python}
            ${lib.getExe poetry} install --all-extras --no-root
          '';
        };
      };
    };
}
```

`pyproject.toml`:
```toml
[tool.poetry]
name = "arguebuf"
version = "2.0.0b24"
description = "A library for loading argument graphs in various formats (e.g., AIF)."
authors = ["Mirko Lenz <info@mirko-lenz.de>"]
license = "MIT"
readme = "README.md"
homepage = "https://recap.uni-trier.de"
repository = "https://github.com/recap-utr/arguebuf-python"
documentation = "https://arguebuf.readthedocs.io/en/latest"
packages = [{ include = "arguebuf" }]

[tool.poetry.scripts]
arguebuf = "arguebuf.cli.app:cli"

[tool.poetry.dependencies]
python = "^3.9"
arg-services = "^1.1.0"
networkx = ">=2.8.8, <4.0"
pendulum = "^2.1.2"
graphviz = "^0.20.1"
lxml = "^4.9.2"
typer = { version = "^0.7.0", extras = ["all"], optional = true }
deepl = { version = "^1.13.0", optional = true }
pygraphviz = { version = "^1.10", optional = true }
multimethod = { version = "^1.9.1", optional = true }

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.1"
pytest-cov = "^4.0.0"
pytest-xdist = "^3.1.0"
deepdiff = { extras = ["murmur"], version = "^6.2.3" }
lxml-stubs = "^0.4.0"

[tool.poetry.group.docs.dependencies]
pdoc = { version = "^12.3.1" }

[tool.poetry.extras]
cli = ["typer", "deepl", "multimethod"]
graphviz = ["pygraphviz"]

[tool.pytest.ini_options]
addopts = "--numprocesses 4 --dist load --cov arguebuf --cov-report term-missing --doctest-modules --ignore arguebuf/cli --ignore data"
doctest_optionflags = "NORMALIZE_WHITESPACE IGNORE_EXCEPTION_DETAIL ELLIPSIS"

[tool.ruff]
# https://beta.ruff.rs/docs/rules
target-version = "py39"
select = ["B", "E", "F", "W"]
ignore = ["E501"]

[tool.ruff.per-file-ignores]
"arguebuf/cli/*.py" = ["B008"]
"arguebuf/model/node.py" = ["B027"]

[tool.ruff.pydocstyle]
convention = "google"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

`poetry.lock`: [Too long, so here is the direct link instead](https://raw.githubusercontent.com/recap-utr/arguebuf-python/beta/poetry.lock)
