### ISSUE TITLE
infinite recursion after adding mkPoetryEnv

### ISSUE THREAD

**Issue by brianmay** [nix-community/poetry2nix#1184]
### Describe the issue

When trying to add `mkPoetryEnv` to my project I get infinite recursion errors.

Unfortunately my nix debugging skills are terrible :-(

If I remove the reference to `x` it works.

### Additional context

Source project: https://github.com/Karaage-Cluster/python-tldap

`flake.nix` (after hacking to try to simplify/fix this problem):
```nix
{
  description = "Python LDAP library";

  inputs.flake-utils.url = "github:numtide/flake-utils";
  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixos-23.05";
  inputs.poetry2nix = {
    url = "github:nix-community/poetry2nix";
    inputs.nixpkgs.follows = "nixpkgs";
  };

  outputs = { nixpkgs, flake-utils, poetry2nix, ... }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        # see https://github.com/nix-community/poetry2nix/tree/master#api for more functions and examples.
        p2n_pkgs = poetry2nix.legacyPackages.${system};
        mkPoetryApplication = p2n_pkgs.mkPoetryApplication;
        mkPoetryEnv = p2n_pkgs.mkPoetryEnv;

        pkgs = nixpkgs.legacyPackages.${system};
        slapd = pkgs.writeShellScriptBin "slapd" ''
          exec ${pkgs.openldap}/libexec/slapd "$@"
        '';
        x = mkPoetryEnv { projectDir = ./.; };

      in {
        packages = rec {
          python-tldap = mkPoetryApplication { projectDir = ./.; };
          default = python-tldap;
        };

        devShells.default =
          pkgs.mkShell { packages = [ x pkgs.libffi slapd pkgs.openldap ]; };
      });
}
```

`pyproject.toml`:
```toml
[tool.poetry]
name = "python-tldap"
version = "1.0.7"
description = "High level python LDAP Library"
authors = ["Brian May <brian@linuxpenguins.xyz>"]
license = "GPL3+"
packages = [
    { include = "tldap" },
]
readme = "README.rst"
homepage = "https://github.com/Karaage-Cluster/python-tldap/"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

[tool.poetry.dependencies]
python = "^3.10"
passlib = "*"
pyasn1 = "*"
ldap3 = "*"
six = "*"
pip = "*"
django = {version = "*", optional = true}
sphinx = {version = "*", optional = true}

[tool.poetry.dev-dependencies]
pytest = "*"
mock = "*"
pytest-runner = "*"
pytest-bdd = "*"
pytest-django = "*"
django = "*"
sphinx = "*"
tox = "*"
flake8 = "*"
twine = "*"
pipenv-to-requirements = "*"
pytest-cov = "*"
isort = "*"
wheel = "*"
bumpversion = "*"

[tool.poetry.extras]
docs = ["sphinx", "django"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

Stack trace:

```
nix build --show-trace
warning: Git tree '/home/brian/tree/unimelb/karaage/python-tldap' is dirty
error:
       … while evaluating the attribute 'drvPath'

       at /nix/store/0b70h37ffm7wkkaqbzhvj18cgjqnwjjk-source/lib/customisation.nix:228:7:

          227|     in commonAttrs // {
          228|       drvPath = assert condition; drv.drvPath;
             |       ^
          229|       outPath = assert condition; drv.outPath;

       … while evaluating the attribute 'buildInputs' of the derivation 'python3.10-python-tldap-1.0.7'

       at /nix/store/0b70h37ffm7wkkaqbzhvj18cgjqnwjjk-source/pkgs/stdenv/generic/make-derivation.nix:303:7:

          302|     // (lib.optionalAttrs (attrs ? name || (attrs ? pname && attrs ? version)) {
          303|       name =
             |       ^
          304|         let

       … while evaluating the attribute 'out.outPath'

       at /nix/store/0b70h37ffm7wkkaqbzhvj18cgjqnwjjk-source/lib/customisation.nix:215:13:

          214|             drvPath = assert condition; drv.${outputName}.drvPath;
          215|             outPath = assert condition; drv.${outputName}.outPath;
             |             ^
          216|           } //

       … while evaluating the attribute 'out.outPath'

       at /nix/store/0b70h37ffm7wkkaqbzhvj18cgjqnwjjk-source/lib/customisation.nix:215:13:

          214|             drvPath = assert condition; drv.${outputName}.drvPath;
          215|             outPath = assert condition; drv.${outputName}.outPath;
             |             ^
          216|           } //

       … while evaluating the attribute 'nativeBuildInputs' of the derivation 'python3.10-bumpversion-0.6.0'

       at /nix/store/0b70h37ffm7wkkaqbzhvj18cgjqnwjjk-source/pkgs/stdenv/generic/make-derivation.nix:303:7:

          302|     // (lib.optionalAttrs (attrs ? name || (attrs ? pname && attrs ? version)) {
          303|       name =
             |       ^
          304|         let

       … while evaluating the attribute 'propagatedBuildInputs' of the derivation 'pip-install-hook'

       at /nix/store/0b70h37ffm7wkkaqbzhvj18cgjqnwjjk-source/pkgs/stdenv/generic/make-derivation.nix:303:7:

          302|     // (lib.optionalAttrs (attrs ? name || (attrs ? pname && attrs ? version)) {
          303|       name =
             |       ^
          304|         let

       … while evaluating the attribute 'out.outPath'

       at /nix/store/0b70h37ffm7wkkaqbzhvj18cgjqnwjjk-source/lib/customisation.nix:215:13:

          214|             drvPath = assert condition; drv.${outputName}.drvPath;
          215|             outPath = assert condition; drv.${outputName}.outPath;
             |             ^
          216|           } //

       … while evaluating the attribute 'nativeBuildInputs' of the derivation 'python3.10-pip-23.1.2'

       at /nix/store/0b70h37ffm7wkkaqbzhvj18cgjqnwjjk-source/pkgs/stdenv/generic/make-derivation.nix:303:7:

          302|     // (lib.optionalAttrs (attrs ? name || (attrs ? pname && attrs ? version)) {
          303|       name =
             |       ^
          304|         let

       error: infinite recursion encountered

       at /nix/store/0b70h37ffm7wkkaqbzhvj18cgjqnwjjk-source/pkgs/stdenv/generic/make-derivation.nix:347:7:

          346|       depsBuildBuild              = lib.elemAt (lib.elemAt dependencies 0) 0;
          347|       nativeBuildInputs           = lib.elemAt (lib.elemAt dependencies 0) 1;
             |       ^
          348|       depsBuildTarget             = lib.elemAt (lib.elemAt dependencies 0) 2;
```
