### ISSUE TITLE
trouble specifying dlib compile options

### ISSUE THREAD

**Issue by jalil-salame** [nix-community/poetry2nix#1186]
### Describe the issue

I was trying to compile dlib with GUI support: https://github.com/NixOS/nixpkgs/blob/nixos-23.05/pkgs/development/libraries/dlib/default.nix#L2

But none of the ways I tried worked (overlay on nixpkgs and overrides in poetry2nix.mkPoetryApplication).

This would be nice to have documented in the README or an additional documentation file

### Additional context

`flake.nix`:
```nix
{
  description = "Application packaged using poetry2nix";

  inputs.flake-utils.url = "github:numtide/flake-utils";
  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
  inputs.poetry2nix = {
    url = "github:nix-community/poetry2nix";
    inputs.nixpkgs.follows = "nixpkgs";
    inputs.flake-utils.follows = "flake-utils";
  };

  outputs = {
    self,
    nixpkgs,
    flake-utils,
    poetry2nix,
  }:
    flake-utils.lib.eachDefaultSystem (system: let
      inherit (poetry2nix.legacyPackages.${system}) mkPoetryApplication;
      overlays = [];
      pkgs = import nixpkgs {inherit system overlays;};
    in {
      packages = {
        myapp = mkPoetryApplication {projectDir = self;};
        default = self.packages.${system}.myapp;
        overrides = poetry2nix.overrides.withDefaults (final: prev: {dlib = prev.dlib.override {guiSupport = true;};});
      };

      devShells.default = pkgs.mkShell {
        packages = [poetry2nix.packages.${system}.poetry];
      };
    });
}
```

`pyproject.toml`:
```toml
[tool.poetry]
name = "myapp"
version = "0.1.0"
description = ""
authors = ["Jalil David Salamé Messina <jalil.salame@gmail.com>"]
readme = "README.md"
packages = [{ include = "myapp" }]

[tool.poetry.dependencies]
python = "^3.10"
numpy = "^1.24.2"
dlib = "^19.24.2"

[tool.poetry.scripts]
daily-face = "myapp:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

`poetry.lock`:
```toml
# This file is automatically @generated by Poetry and should not be changed by hand.

[[package]]
name = "dlib"
version = "19.24.2"
description = "A toolkit for making real world machine learning and data analysis applications"
category = "main"
optional = false
python-versions = "*"
files = [
    {file = "dlib-19.24.2.tar.gz", hash = "sha256:2d4f618073bc6b297aa01ce05595a2d32b5b37e69cafd99f796e77346f6dcfb5"},
]

[metadata]
lock-version = "2.0"
python-versions = "^3.10"
content-hash = "a1c8b54e82d6929ae180c4d73b5db80865d4f896344548e5111b7255d128c111"
```
