### ISSUE TITLE
venv syslink

### ISSUE THREAD

**Issue by bigluck** [nix-community/poetry2nix#1216]
Hi, this project is really amazing!

These days I'm trying to produce a replicable development environment that my team can use, and poetry2nix looks like an excellent solution.

However, one of the needs is that the `~/venv` folder is populated with the same content we usually have by launching `python3 -m venv venv`; in general, it simplifies the configuration of our IDEs (VS Code, etc), especially when we need to navigate the dependencies' source code.

I'm doing some POC with this very simple shell.nix file:

```nix
{ pkgs ? import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/6c43a3495a11e261e5f41e5d7eda2d71dae1b2fe.tar.gz") {} }:

let
  myAppEnv = pkgs.poetry2nix.mkPoetryEnv {
    python = pkgs.python311;
    projectDir = ./.;
    editablePackageSources = {
      my-app = ./src;
    };
    preferWheels = true;
  };
in myAppEnv.env.overrideAttrs (oldAttrs: {
  buildInputs = [
    pkgs.curl
    pkgs.jq
  ];
})
```

The Poetry file is very basic:
```toml
[tool.poetry]
name = "my-test"
version = "0.0.1"
description = "Test"
authors = ["Big"]
readme = "README.md"
packages = [{include = "my_test"}]

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.31.0"

[tool.poetry.group.dev.dependencies]
mypy = "^1.4.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

and using direnv the new shell is automatically activated when I open the folder in my terminal.
python works as expected

```bash
$ which python
/nix/store/phkin80lf2iblj4jm909qdxr67hs358m-python3-3.11.2-env/bin/python
```

and the dependencies are sandboxed, as expected:

```python
python
Python 3.11.2 (main, Apr  5 2023, 14:58:15) [Clang 11.1.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> print(requests.__path__)
['/nix/store/phkin80lf2iblj4jm909qdxr67hs358m-python3-3.11.2-env/lib/python3.11/site-packages/requests']
```

but, the entire venv is not on the venv folder (it's fine, it's how nix works)... what I would like to do is to have a hook after the shell activation that creates a venv symlink to the store folder, and in general I think it can be a helpful build-in feature to provide OOtB.

How can I do?

Thanks so much again.
