### ISSUE TITLE
Inconsistent behaviours using nix-shell with poetry2nix

### ISSUE THREAD

**Issue by bigluck** [nix-community/poetry2nix#1226]
### Describe the issue

I'm trying to replace my docker-base development environment in favor of nix, and it looks `poetry2nix` does what I'm looking for.

But still, after a few days of work, I cannot connect all the dots.

I would like to:
- ✅ activate a subshell (using `direnv` or `nix-shell`) with python 3.11 and all my dependencies
- ✅ run my exported script `[script-name]`
- ❌ invoke my script using python `python ./my/path.py`
- ❌ run my script using poetry `poetry run [script-name]`

The last 2 points don't work as I hoped, and I can't understand why; in particular if I run python in interactive mode I can import my Python scripts, but passing them to the Python interpreter fails.

### Additional context

Even if it's a basic project, I've committed my code here: [bigluck/poetry2nix-venv](https://github.com/bigluck/poetry2nix-venv).

But in general this is my `pyproject.toml` file:

```toml
[tool.poetry]
name = "my-python-nix-test"
version = "0.0.1"
description = "Test"
authors = ["BigLuck"]
readme = "README.md"
packages = [{include = "my_python_nix_test"}]

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.31.0"

[tool.poetry.scripts]
my-python-nix-test = "my_python_nix_test.a:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

and this is the `shell.nix` file that uses `poetry2nix`:

```nix
{ pkgs ? import <nixpkgs> {} }:

let
  myAppEnv = pkgs.poetry2nix.mkPoetryEnv {
    python = pkgs.python311;
    projectDir = ./.;
    editablePackageSources = {
      my_python_nix_test = ./my_python_nix_test;
    };
    preferWheels = true;
  };
in myAppEnv.env.overrideAttrs (oldAttrs: {
  buildInputs = [
    # pkgs.poetry
    # (pkgs.poetry.override { python = pkgs.python311; })
  ];
  shellHook =
    ''
    ln -sfT $nativeBuildInputs ./venv
    '';
})
```

Still, you can find all the details on my git repo:  [bigluck/poetry2nix-venv](https://github.com/bigluck/poetry2nix-venv).

Can anybody help me understand what's going on and how I can fix it?
Thanks
