### ISSUE TITLE
macOS error: Missing suitable source/wheel file entry for torch

### ISSUE THREAD

**Issue by Atry** [nix-community/poetry2nix#1311]
### Describe the issue
When running `nix build` on macOS, I got the following error message
```
error:
       … while calling the 'derivationStrict' builtin

         at //builtin/derivation.nix:9:12: (source not available)

       … while evaluating derivation 'python3-3.10.12-env'
         whose name attribute is located at /nix/store/08h2h51hi504b0n2ak6jn7b4hrfrn1h7-source/pkgs/stdenv/generic/make-derivation.nix:300:7

       … while evaluating attribute 'passAsFile' of derivation 'python3-3.10.12-env'

         at /nix/store/08h2h51hi504b0n2ak6jn7b4hrfrn1h7-source/pkgs/build-support/trivial-builders/default.nix:88:7:

           87|       inherit buildCommand name;
           88|       passAsFile = [ "buildCommand" ]
             |       ^
           89|         ++ (derivationArgs.passAsFile or []);

       error: Missing suitable source/wheel file entry for torch
```

On the other hand, `nix develop -c poetry install` works well:
```
Installing dependencies from lock file

Package operations: 8 installs, 0 updates, 0 removals

  • Installing markupsafe (2.1.3)
  • Installing mpmath (1.3.0)
  • Installing filelock (3.12.4)
  • Installing jinja2 (3.1.2)
  • Installing networkx (3.1)
  • Installing sympy (1.12)
  • Installing typing-extensions (4.7.1)
  • Installing torch (2.0.1)
```
### Additional context

Minimized reproduction: https://gist.github.com/Atry/14af26cf2e7e85559bbd43ef36584be7

`flake.nix`:
```nix
{
  outputs = { self, nixpkgs, flake-utils, poetry2nix }:
    flake-utils.lib.eachDefaultSystem (system: let
      pkgs = nixpkgs.legacyPackages.${system};
    in {

      devShells.default = pkgs.mkShell {
        buildInputs = with pkgs; [
          poetry
        ];
      };

      packages.default = poetry2nix.legacyPackages.${system}.mkPoetryEnv {
        projectDir = ./.;
        python = pkgs.python3;
        preferWheels = true;
      };
    });

}
```

`pyproject.toml`:
```toml
[tool.poetry]
name = "poetry2nix-bug-report"
version = "0.1.0"
description = ""
authors = ["Yang, Bo <yang-bo@yang-bo.com>"]
readme = "README.md"

[[tool.poetry.source]]
name = "cuda-torch"
url = "https://download.pytorch.org/whl/cu118"
priority = "supplemental"


[[tool.poetry.source]]
name = "PyPI"
priority = "primary"

[tool.poetry.dependencies]
python = "^3.10"

torch = [
  { platform = "darwin", version = "*", source = "pypi" },
  { platform = "linux", version = "*", source = "cuda-torch" },
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

`poetry.lock` and `flake.lock`:
see https://gist.github.com/Atry/14af26cf2e7e85559bbd43ef36584be7
