### ISSUE TITLE
Issue with dealing with submodules in nix-shell

### ISSUE THREAD

**Issue by tobiasBora** [nix-community/poetry2nix#1326]
### Describe the issue

I want to use `nix develop` to get dropped into a shell where I can develop a software. When I type `nix develop`, I get dropped into a shell and I had the nice surprise to see that it automatically created a binary with the name of the program. But it fails when I run it:
```
$ paddingoracle
Traceback (most recent call last):
  File "/tmp/nix-shell.t7SQAH/tmp.vRG4fOlKmi/bin/paddingoracle", line 5, in <module>
    from paddingoracle.server import main
ModuleNotFoundError: No module named 'paddingoracle'
```
It turns out that the program is in a sub-folder:
```
$ ls paddingoracle/
aes.py  server.py
```
The binary created by peotry2nix does see this:
```
$ cat $(which paddingoracle)
#!/nix/store/abax98471z8fshv4b9p46bkh3lxmpy0z-python3-3.10.9/bin/python3.10
# -*- coding: utf-8 -*-
import re
import sys
from paddingoracle.server import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```
unfortunately when I run it it fails, my guess is that python only import subfolders that are in the directory of the script, but the script loaded by nix-develop is located in `/tmp` not where the actual project is. To solve this, I can manually copy the script, but it is not really practical:
```
$ cp $(which paddingoracle) padd
$ ./padd
Using random key 639c9da1bca91656fdf8c3a70628425e
Listening on 0.0.0.0:8080
```
You can find the project with the flake in https://github.com/aimileus/paddingoracle (it is a really tiny script).

### Additional context

The whole project is in https://github.com/aimileus/paddingoracle

`default.nix`/`shell.nix`/`flake.nix`:
```nix
{
  # To run: just install nix and type:
  # nix run .
  # in the current folder.
  description = "Padding oracle server for homework";

  inputs.flake-utils.url = "github:numtide/flake-utils";

  outputs = { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachDefaultSystem
      (system:
        let pkgs = nixpkgs.legacyPackages.${system}; in
        {
          packages.default = pkgs.poetry2nix.mkPoetryApplication {
            projectDir = ./.;
            # Otherwise it compiles everything... takes ages
            preferWheels = true;
          };
        }
      );
}
```

`pyproject.toml`:
```toml
[tool.poetry]
name = "paddingoracle"
version = "0.1.0"
description = ""
authors = ["Emiel Wiedijk <13463911+aimileus@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.6"
cryptography = "^40.0.2"

[tool.poetry.scripts]
paddingoracle = "paddingoracle.server:main"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

```

`poetry.lock`:
```toml
```
