### ISSUE TITLE
Unable to use nix-shell command with `poetry2nix.mkPoetryEnv` caused by known issues in `requests`

### ISSUE THREAD

**Issue by comilao** [nix-community/poetry2nix#1331]
### Describe the issue

I would like to enter nix-shell via `nix-shell shell.nix` command. 

The package `pystarport` requires `poetry` to build, however it produces error like this
```
       error: Package ‘python3.11-requests-2.29.0’ in /nix/store/269zw9pz0z9aazmikf4dkfp0wdzrbv0n-nixpkgs-src/pkgs/development/tools/poetry2nix/poetry2nix/pkgs/poetry/poetry.lock:0 is marked as insecure, refusing to evaluate.


       Known issues:
        - CVE-2023-32681
```

I suspect it is because [default.nix](https://github.com/nix-community/poetry2nix/blob/master/pkgs/poetry/default.nix) for poetry at this repo is different from the [default.nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/poetry2nix/poetry2nix/pkgs/poetry/default.nix) for poetry in `nixpkgs` repo, but I am not sure what I can do from my side, as I am using `poetry2nix` from the nixpkgs repo.

My temporary solution is exporting an environment variable and pass it to `nix-shell --pure --keep NIXPKGS_ALLOW_INSECURE shell.nix`, appreciate if you could help me with this issue. Thanks in advance!

### Additional context

`default.nix`/`shell.nix`/`flake.nix`:
```nix
# shell.nix
{ system ? builtins.currentSystem, pkgs ? import ./nix { inherit system; } }:

pkgs.mkShell {
  buildInputs = [
    pkgs.test-env
  ];
}
```

```nix
# nix/testenv.nix
{ poetry2nix, lib, python311 }:
poetry2nix.mkPoetryEnv {
  projectDir = ../.;
  python = python311;
  overrides = poetry2nix.overrides.withDefaults (lib.composeManyExtensions [
    (self: super:
      let
        buildSystems = {
          pystarport = [ "poetry" ];
          durations = [ "setuptools" ];
          multitail2 = [ "setuptools" ];
        };
      in
      lib.mapAttrs
        (attr: systems: super.${attr}.overridePythonAttrs
          (old: {
            nativeBuildInputs = (old.nativeBuildInputs or [ ]) ++ map (a: self.${a}) systems;
          }))
        buildSystems
    )
  ]);
}
```

```nix
# nix/default.nix
{ sources ? import ./sources.nix, system ? builtins.currentSystem, ... }:
import sources.nixpkgs {
  overlays = [
    (_: pkgs: { test-env = pkgs.callPackage ./testenv.nix { }; })
  ];
  config = { };
  inherit system;
}
```

`pyproject.toml`:
```toml
[tool.poetry]
authors = ["Your Name <you@example.com>"]
description = ""
name = "try-nix"
readme = "README.md"
version = "0.1.0"

[tool.poetry.dependencies]
pystarport = {git = "https://github.com/crypto-com/pystarport", branch = "main", rev = "a8f7f5fb38eb5eccad379896486c0d418027d6ce"}
python = "^3.11"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]
```

`poetry.lock`:
```toml
```
