### ISSUE TITLE
Development environment for library

### ISSUE THREAD

**Issue by vleni** [nix-community/poetry2nix#1433]
### Describe the issue

I want to create a nix environment for developing a python package. It should support:
1. `python3 -c 'import package'` should work as if `package` has already been installed, so it should work when executed from a subdirectory, say `examples/`.
2. `nix build` should build the python package and output it somewhere

Currently with `mkPoetryEnv`, `python3 -c 'import package'` only succeeds if `package/` is in `$PWD`. Otherwise it says `no module named ...`

### Additional context

For a minimal example, create the following file structure
```
.
|- flake.nix
|- pyproject.toml
|- ./locomotive
     |- __init__.py
|- ./example
```
```nix
# flake.nix

{
  description = "Python Lib";

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
    flake-parts.url = "github:hercules-ci/flake-parts";
    poetry2nix = {
      url = "github:nix-community/poetry2nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = inputs @ {
    self,
    nixpkgs,
    flake-parts,
    poetry2nix,
    ...
  } : flake-parts.lib.mkFlake { inherit inputs; } {
    flake = {
    };
    systems = [
      "x86_64-linux"
      "x86_64-darwin"
    ];
    perSystem = { system, pkgs, ... }: let
      p2n = poetry2nix.lib.mkPoetry2Nix { inherit pkgs; };
      args = {
        projectDir = ./.;
        python = pkgs.python311;
        editablePackageSources = {
          locomotive = ./locomotive;
        };
      };
      pp = p2n.mkPoetryPackages args;
      env = p2n.mkPoetryEnv args;
    in rec {
      packages = {
        default = pkgs.lib.last pp.poetryPackages;
      };
      devShells.default = pkgs.mkShell {
        nativeBuildInputs = [
          pp.python
          env
        ];
      };
    };
  };
}
```

```toml
# pyproject.toml

[tool.poetry]
name = "locomotive"
version = "0.0.1"
description = "Example python library"
authors = []

[tool.poetry.dependencies]
python = "^3.11"

[tool.poetry.group.dev.dependencies]
pylint = "^2.17.6"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

```python
# locomotive/__init__.py
def f():
    return 123;
```
Then execute
```sh
poetry lock
nix develop
cd examples
python3 -c 'import locomotive; print(locomotive.f())'
```
the line `import locomotive` fails.

I couldn't find many examples in `mkPoetryPackages` but I'm pretty sure the `packages.default` is wrong as well. Is there a way to make this work?
