### ISSUE TITLE
multidict: Found duplicated packages in closure for dependency 'pip'

### ISSUE THREAD

**Issue by pmiddend** [nix-community/poetry2nix#1437]
### Describe the issue

I'm trying to build an application with poetry2nix which involves `aiohttp` and `multidict` (see pyproject attached). It tells me 

```
python3.11-multidict> Found duplicated packages in closure for dependency 'pip':
python3.11-multidict>   pip 23.2.1 (/nix/store/slhj69him45n2pck7wkknnffi4ay0jy0-python3.11-pip-23.2.1/lib/python3.11/site-packages/pip-23.2.1.dist-info)
python3.11-multidict>   pip 23.2.1 (/nix/store/386b8qf339cv2w8lqak3h0cv2933kycn-python3.11-pip-23.2.1/lib/python3.11/site-packages/pip-23.2.1.dist-info)
python3.11-multidict> Package duplicates found in closure, see above. Usually this happens if two packages depend on different version of the same dependency.
```

Is there any way to debug this further on my own?

### Additional context

`pyproject.toml`:
```toml
[tool.poetry]
name = "projectname"
version = "1.0.0"
description = ""
authors = []
license = "GPL-3.0-or-later"

[tool.poetry.dependencies]
python = ">=3.8, <3.12"

h5py = "3.8.0"
SQLAlchemy = { version = "1.4.49", extras = ["asyncio"] }
cryptography = '40.0.2'
typed-argument-parser = '1.7.2'
pydantic = '1.10.7'
numpy = '1.23.5'
pint = '0.16.1'

pymysql = '1.1.0'

openpyxl = "3.0.9"

python-dateutil = "2.8.2"
quart = "0.17.0"
Quart-CORS = "0.5.0"
werkzeug = "2.1.2"
aiosqlite = "0.17.0"
asyncmy = "0.2.7"

pytz = "2021.3"
python-magic = "0.4.24"
randomname = "0.1.5"
aiohttp = "3.9.1"
alembic = "1.7.7"
hypercorn = "0.13.2"
Pillow = "9.4.0"
lark = "1.1.2"
structlog = "22.1.0"
structlog-overtime = "1.0.1"
greenlet = "1.1.3"

[tool.poetry.dev-dependencies]
black = '22.3.0'
pathspec = "0.10.1"
types-pytz = "2021.3.6"
pylint = '2.15.4'
pyfakefs = '4.7.0'
openpyxl-stubs = "0.1.25"
pytest = '6.2.5'
hypothesis = '6.27.1'
pytest-cov = '2.12.1'
types-python-dateutil = "2.8.3"
types-requests = "2.26.0"
types-PyYAML = '5.4.12'
pytest-asyncio = "0.17.2"
isort = "5.12.0"
pytest-subprocess = "1.4.1"
sqlalchemy2-stubs = "0.0.2a35"
fawltydeps = "0.12.0"
```
