### ISSUE TITLE
Latest poetry2nix master and nixos-unstable crash on nixos/nix:2.19.2 Docker image

### ISSUE THREAD

**Issue by l0b0** [nix-community/poetry2nix#1459]
### Describe the issue

See [commit](https://gitlab.com/engmark/mypy-exercises/-/merge_requests/474/diffs?commit_id=c2d025f293c78b7dcafe6b088c22c5acd4d9783c) and [job output](https://gitlab.com/engmark/mypy-exercises/-/jobs/5719035381) - I can't reproduce on Nix 2.18.1 locally.

### Additional context

Relevant job output:

```
$ nix-shell --pure --run true
error:
       … while calling the 'derivationStrict' builtin
         at /derivation-internal.nix:9:12:
            8|
            9|   strict = derivationStrict drvAttrs;
             |            ^
           10|
       … while evaluating derivation 'interactive-python3-3.11.6-environment'
         whose name attribute is located at /nix/store/4h8lf8rijg46drx6gc8j9wxiia755cqq-nixpkgs-src/pkgs/stdenv/generic/make-derivation.nix:348:7
       … while evaluating attribute 'nativeBuildInputs' of derivation 'interactive-python3-3.11.6-environment'
         at /nix/store/4h8lf8rijg46drx6gc8j9wxiia755cqq-nixpkgs-src/pkgs/stdenv/generic/make-derivation.nix:392:7:
          391|       depsBuildBuild              = elemAt (elemAt dependencies 0) 0;
          392|       nativeBuildInputs           = elemAt (elemAt dependencies 0) 1;
             |       ^
          393|       depsBuildTarget             = elemAt (elemAt dependencies 0) 2;
       (stack trace truncated; use '--show-trace' to show the full trace)
       error: function 'anonymous lambda' called with unexpected argument 'flit-core'
       at /nix/store/hj67q03l4bs3blb3bl29pvwzyihh6l5f-xll3z18vgn7xyiiipp506rldlyvlj4np-source/pkgs/development/python-modules/wheel/default.nix:1:1:
            1| { lib
             | ^
            2| , buildPythonPackage
```

`shell.nix`:
```nix
let
  sources = import ./nix/sources.nix;
  pkgs = import sources.nixpkgs {};
  poetry2nix = import sources.poetry2nix {};
  pythonWithPackages = pkgs.python3.withPackages (ps: [
    ps.pip
  ]);
  poetryEnv = poetry2nix.mkPoetryEnv {
    inherit (pythonWithPackages) python;
    projectDir = builtins.path {
      path = ./.;
      name = "mypy-exercises";
    };
    overrides = poetry2nix.overrides.withDefaults (
      self: super: {
        attrs = super.attrs.overridePythonAttrs (
          old: {
            propagatedBuildInputs =
              old.propagatedBuildInputs
              or []
              ++ [
                self.hatch-fancy-pypi-readme
                self.hatch-vcs
                self.hatchling
              ];
          }
        );
        urllib3 = super.urllib3.overridePythonAttrs (
          old: {
            propagatedBuildInputs =
              old.propagatedBuildInputs
              or []
              ++ [
                self.hatchling
              ];
          }
        );
      }
    );
  };
in
  poetryEnv.env.overrideAttrs (
    _oldAttrs: {
      buildInputs = [
        pkgs.alejandra
        pkgs.cacert
        pkgs.check-jsonschema
        pkgs.curl
        pkgs.deadnix
        pkgs.gitFull
        pkgs.jq
        pkgs.niv
        pkgs.nodePackages.prettier
        pkgs.poetry
        pkgs.shfmt
        pkgs.statix
        pkgs.yq-go
      ];
      env = {
        LOCALE_ARCHIVE = "${pkgs.glibcLocales}/lib/locale/locale-archive";
      };
      shellHook = ''
        ln --force --no-target-directory --symbolic "${pythonWithPackages}/bin/python" python
      '';
    }
  )
```

`pyproject.toml`:
```toml
[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]

[tool.coverage.report]
exclude_lines = [
  'if TYPE_CHECKING:',
  'pragma: no cover'
]
fail_under = 100

[tool.coverage.run]
branch = true
omit = [
  "src/why/ide_hints.py",
  "src/why/name_reuse.py"
]
source = [
  "."
]

[tool.isort]
profile = "black"

[tool.mypy]
strict = true

[[tool.mypy.overrides]]
ignore_missing_imports = true
module = [
  "pytest_subtests"
]

[tool.poetry]
authors = ["Victor Engmark <victor@engmark.name>"]
description = "Exercises to learn about Python type hinting using mypy."
license = "Creative Commons Attribution-ShareAlike 4.0 International License"
name = "mypy-exercises"
version = "0.1.0"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.group.dev.dependencies]
black = "*"
boto3-stubs = {version = "*", extras = ["s3control"]}
coverage = "*"
gitlint = "*"
isort = "*"
language-formatters-pre-commit-hooks = "*"
mutmut = "*"
mypy = "*"
pre-commit = "*"
pylint = "*"
pytest = "*"
pytest-randomly = "*"
pytest-subtests = "*"
shellcheck-py = "*"

[tool.pylint.MASTER]
disable = [
  "duplicate-code",
  "missing-docstring",
  "too-few-public-methods"
]
enable = [
  "bad-inline-option",
  "c-extension-no-member",
  "deprecated-pragma",
  "file-ignored",
  "raw-checker-failed",
  "use-symbolic-message-instead",
  "useless-suppression"
]
fail-on = [
  "I"
]
```

[`poetry.lock`](https://gist.github.com/l0b0/e8aa81735f253df777f602ddcce577e2)

Potentially also related to [this issue](https://discourse.nixos.org/t/function-anonymous-lambda-called-with-unexpected-argument/34267/7)?

### Attempted workarounds

[Downgrade Nix to 2.18.1](https://gitlab.com/engmark/mypy-exercises/-/merge_requests/474/diffs?commit_id=7189bc328d0bba8516d59b44d79f5551aacdc389), the same version as locally, did not work:

```console
$ nix-shell --pure --run true
error:
       … while calling the 'derivationStrict' builtin
         at /builtin/derivation.nix:9:12: (source not available)
       … while evaluating derivation 'interactive-python3-3.11.6-environment'
         whose name attribute is located at /nix/store/4h8lf8rijg46drx6gc8j9wxiia755cqq-nixpkgs-src/pkgs/stdenv/generic/make-derivation.nix:348:7
       … while evaluating attribute 'nativeBuildInputs' of derivation 'interactive-python3-3.11.6-environment'
         at /nix/store/4h8lf8rijg46drx6gc8j9wxiia755cqq-nixpkgs-src/pkgs/stdenv/generic/make-derivation.nix:392:7:
          391|       depsBuildBuild              = elemAt (elemAt dependencies 0) 0;
          392|       nativeBuildInputs           = elemAt (elemAt dependencies 0) 1;
             |       ^
          393|       depsBuildTarget             = elemAt (elemAt dependencies 0) 2;
       (stack trace truncated; use '--show-trace' to show the full trace)
       error: function 'anonymous lambda' called with unexpected argument 'flit-core'
       at /nix/store/da5fzqpg9jfxjfc8g70lydb8b3688p1p-rfd98iac9jigcrp42c6s9ry90z0fhaaa-source/pkgs/development/python-modules/wheel/default.nix:1:1:
            1| { lib
             | ^
            2| , buildPythonPackage
```

[Downgrade nixpkgs to 23.11](https://gitlab.com/engmark/mypy-exercises/-/merge_requests/474/diffs?commit_id=615595244502dd50ad91e2d6528d00f2071f21f7), same as locally, did not work:

```console
$ nix-shell --pure --run true
error:
       … while calling the 'derivationStrict' builtin
         at /derivation-internal.nix:9:12:
            8|
            9|   strict = derivationStrict drvAttrs;
             |            ^
           10|
       … while evaluating derivation 'interactive-python3-3.11.6-environment'
         whose name attribute is located at /nix/store/0iq70a9zqjrh7yb6f9jshg5vpxj24879-nixpkgs-src/pkgs/stdenv/generic/make-derivation.nix:348:7
       … while evaluating attribute 'nativeBuildInputs' of derivation 'interactive-python3-3.11.6-environment'
         at /nix/store/0iq70a9zqjrh7yb6f9jshg5vpxj24879-nixpkgs-src/pkgs/stdenv/generic/make-derivation.nix:392:7:
          391|       depsBuildBuild              = elemAt (elemAt dependencies 0) 0;
          392|       nativeBuildInputs           = elemAt (elemAt dependencies 0) 1;
             |       ^
          393|       depsBuildTarget             = elemAt (elemAt dependencies 0) 2;
       (stack trace truncated; use '--show-trace' to show the full trace)
       error: function 'anonymous lambda' called with unexpected argument 'flit-core'
       at /nix/store/hj67q03l4bs3blb3bl29pvwzyihh6l5f-xll3z18vgn7xyiiipp506rldlyvlj4np-source/pkgs/development/python-modules/wheel/default.nix:1:1:
            1| { lib
             | ^
            2| , buildPythonPackage
```

[Both of the above](https://gitlab.com/engmark/mypy-exercises/-/merge_requests/474/diffs?commit_id=49f1344501567b67bcd323d5d51ac96dfeeb3bfa), even closer to my local setup, did not work:

```console
$ nix-shell --pure --run true
error:
       … while calling the 'derivationStrict' builtin
         at /builtin/derivation.nix:9:12: (source not available)
       … while evaluating derivation 'interactive-python3-3.11.6-environment'
         whose name attribute is located at /nix/store/0iq70a9zqjrh7yb6f9jshg5vpxj24879-nixpkgs-src/pkgs/stdenv/generic/make-derivation.nix:348:7
       … while evaluating attribute 'nativeBuildInputs' of derivation 'interactive-python3-3.11.6-environment'
         at /nix/store/0iq70a9zqjrh7yb6f9jshg5vpxj24879-nixpkgs-src/pkgs/stdenv/generic/make-derivation.nix:392:7:
          391|       depsBuildBuild              = elemAt (elemAt dependencies 0) 0;
          392|       nativeBuildInputs           = elemAt (elemAt dependencies 0) 1;
             |       ^
          393|       depsBuildTarget             = elemAt (elemAt dependencies 0) 2;
       (stack trace truncated; use '--show-trace' to show the full trace)
       error: function 'anonymous lambda' called with unexpected argument 'flit-core'
       at /nix/store/da5fzqpg9jfxjfc8g70lydb8b3688p1p-rfd98iac9jigcrp42c6s9ry90z0fhaaa-source/pkgs/development/python-modules/wheel/default.nix:1:1:
            1| { lib
             | ^
            2| , buildPythonPackage
```
