### ISSUE TITLE
can't read pyproject.toml: No such file or directory

### ISSUE THREAD

**Issue by dsalaza4** [nix-community/poetry2nix#1491]
### Describe the issue
I am getting a `sed: can't read pyproject.toml: No such file or directory` error during `patchPhase` when running `mkPoetryEnv`:

```
building '/nix/store/hzkkcrsy2w377l72icarcj8m7nngapml-python3.11-mkdocs-material-9.5.3.drv'...
Sourcing python-remove-tests-dir-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh
Sourcing wheel setup hook
Using wheelUnpackPhase
Sourcing pypa-install-hook
Using pypaInstallPhase
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
Sourcing python-namespaces-hook
Sourcing python-catch-conflicts-hook.sh
Running phase: unpackPhase
Executing wheelUnpackPhase
Finished executing wheelUnpackPhase
Running phase: patchPhase
sed: can't read pyproject.toml: No such file or directory
/nix/store/sf52i9wcklk5i5f2w15p0kng8dq3qqwx-stdenv-darwin/setup: line 140: pop_var_context: head of shell_variables not a function context
error: builder for '/nix/store/hzkkcrsy2w377l72icarcj8m7nngapml-python3.11-mkdocs-material-9.5.3.drv' failed with exit code 2;
```

### Additional context

`default.nix`:
```nix
poetry2nix.mkPoetryEnv {
  preferWheels = true;
  projectDir = ./.;
  python = pkgs.python311;
};
```

`pyproject.toml`:
```toml
[tool.poetry]
name = "makes-docs-runtime"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
mkdocs-material = "9.5.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```
