### ISSUE TITLE
[bug] platform_machine reported wrong on Arm machines lead to Missing suitable source/wheel file entry errors

### ISSUE THREAD

**Issue by heimalne** [nix-community/poetry2nix#1609]
### Describe the issue

In our project we have a dependency that should use a normal package `tensorflow` on all platforms except on arm64 macs; there it should use a special, other package `tensorflow-macos`.

A raw `poetry lock && poetry install` without Nix works as expected on all machines.

However, on my arm64 M1 Mac poetry2nix tries to download the normal tensorflow package when it shouldn't:

```shell
$ nix-build ...
error: Missing suitable source/wheel file entry for tensorflow
```

May it have an issue with multiple markers?

### Additional context

Running on an M1 arm64 Mac with Python 3.9.18 with a `pyproject.toml`:

```toml
...
[tool.poetry.dependencies]
tensorflow = {version = "2.9.0", markers = "sys_platform != \"darwin\" or platform_machine != \"arm64\""}
tensorflow-macos = {version = "2.9.0", markers = "sys_platform == \"darwin\" and platform_machine == \"arm64\""}
tensorflow-metal = {version = "0.4.0", markers = "sys_platform == \"darwin\" and platform_machine == \"arm64\""}
```
