### ISSUE TITLE
Pyright preferring some other python over poetry2nix's

### ISSUE THREAD

**Issue by PartyWumpus** [nix-community/poetry2nix#1637]
### Describe the issue
If pyright is installed via a p2n flake, either from nixpkgs or from the wheel or built as a python package, it won't use the right version of python.

For example, if I run `which python`, it'll be in `/nix/store/ibzll-python3-3.11.9-env/bin/python`, but if I run pyright in verbose mode, it'll be looking around in `/nix/store/lpi16513bai8kg2bd841745vzk72475x-python3-3.11.9/lib/python3.11/`. 

Pyright works totally fine if given the correct path via `--pythonpath`, so my current workaround to get pyright to work is this, which feels like a terrible solution.

```nix
(pkgs.writeShellScriptBin "pyright" ''${pkgs.pyright}/bin/pyright --pythonpath `which python3` "$@" '')
(pkgs.writeShellScriptBin "pyright-langserver" ''${pkgs.pyright}/bin/pyright-langserver --pythonpath `which python3` "$@" '')
(pkgs.writeShellScriptBin "pyright-python" ''${pkgs.pyright}/bin/pyright-python --pythonpath `which python3` "$@" '')
(pkgs.writeShellScriptBin "pyright-python-langserver" ''${pkgs.pyright}/bin/pyright-python-langserver --pythonpath `which python3` "$@" '')
```

Not sure if this is properly fixable on your end, but might be fixed if there was a way to just add the python path as `PYTHONPATH`? I suppose I could just run ```export PYTHONPATH=`which python` ``` when the shell starts, although i'm not 100% sure how to do that, not experienced enough with nix yet.

It still uses the wrong python path even if python isn't in the original environment at all, so it's not just a weird inheriting from my environment bug afaict.

### Additional context

The usecase is just trying to make an easy to use development environment for a project where the python dependencies are listed with poetry.

`default.nix`/`shell.nix`/`flake.nix`:
```nix
{
  description = "Decky development environment";
  # pulls in the python deps from poetry

  inputs = {
    flake-utils.url = "github:numtide/flake-utils";
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    poetry2nix = {
      url = "github:nix-community/poetry2nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = { self, nixpkgs, flake-utils, poetry2nix }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = import nixpkgs { inherit system; };
        p2n = (poetry2nix.lib.mkPoetry2Nix { inherit pkgs; });
      in {
        devShells.default = (p2n.mkPoetryEnv {
          projectDir = self + "/backend";
          # pyinstaller fails to compile so precompiled it is
          overrides = p2n.overrides.withDefaults (final: prev: {
            pyinstaller = prev.pyinstaller.override { preferWheel = true; };
            pyright = null;
          });
        }).env.overrideAttrs (oldAttrs: {
          buildInputs = with pkgs; [
            nodejs_22
            nodePackages.pnpm
            poetry
            # "temporary" "solution" to pyright not being able to see the pythonpath properly.
            (pkgs.writeShellScriptBin "pyright" ''
              ${pkgs.pyright}/bin/pyright --pythonpath `which python3` "$@" '')
            (pkgs.writeShellScriptBin "pyright-langserver" ''
              ${pkgs.pyright}/bin/pyright-langserver --pythonpath `which python3` "$@" '')
            (pkgs.writeShellScriptBin "pyright-python" ''
              ${pkgs.pyright}/bin/pyright-python --pythonpath `which python3` "$@" '')
            (pkgs.writeShellScriptBin "pyright-python-langserver" ''
              ${pkgs.pyright}/bin/pyright-python-langserver --pythonpath `which python3` "$@" '')
          ];
        });
      });
}
```

as you can see we have very few libraries used, but I'd much rather have this kept automatically in sync with p2n than having to remember to update two things every time.
`backend/pyproject.toml`:
```toml
[tool.poetry]
name = "decky-loader"
version = "0.0.0"  # the real version will be autogenerated
description = "A plugin loader for the Steam Deck"
license = "GPLv2"
authors = []
packages = [
    {include = "decky_loader"},
    {include = "decky_loader/main.py"}
]
include = ["decky_loader/static/*"]

[tool.poetry.dependencies]
python = ">=3.10,<3.13"

aiohttp = "^3.9.5"
aiohttp-jinja2 = "^1.5.1"
aiohttp-cors = "^0.7.0"
watchdog = "^2.1.7"
certifi = "*"
packaging = "^23.2"
multidict = "^6.0.5"

[tool.poetry.group.dev.dependencies]
pyinstaller = "^5.13.0"
pyright = "^1.1.335"

[tool.poetry.scripts]
decky-loader = 'decky_loader.main:main'

[tool.pyright]
strict = ["*"]

[tool.poetry-dynamic-versioning]
enable = true

[tool.poetry-dynamic-versioning.substitution]
# don't replace version in decky_plugin.py
files = []

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning>=1.0.0,<2.0.0"]
build-backend = "poetry_dynamic_versioning.backend"
```

the lock file is 700 lines long so i'm not going to paste it all here, but it's [visible here](https://github.com/SteamDeckHomebrew/decky-loader/blob/websockets/flake.nix/backend/poetry.lock) if it could be relevant
