### ISSUE TITLE
`editablePackageSources` doesn't work for packages in a `src` directory

### ISSUE THREAD

**Issue by MartinEekGerhardsen** [nix-community/poetry2nix#1641]
### Describe the issue

When a package is in a `src` directory, the `editablePackageSources` attribute doesn't work. 

### Additional context
Set up a package `app` in the main directory, with a single `__init__.py` file:

```python
def main():
    print("test")
```

If the `flake.nix` and `pyproject.toml` files are set up like this: 

`default.nix`/`shell.nix`/`flake.nix`:
```nix
{
  description = "Application packaged using poetry2nix";

  inputs = {
    flake-utils.url = "github:numtide/flake-utils";
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable-small";
    poetry2nix = {
      url = "github:nix-community/poetry2nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = { self, nixpkgs, flake-utils, poetry2nix }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = nixpkgs.legacyPackages.${system};
        inherit (poetry2nix.lib.mkPoetry2Nix { inherit pkgs; }) mkPoetryEnv;

      in
      {
        packages.myapp-env = mkPoetryEnv {
          projectDir = self;
          editablePackageSources.app = ./.;
        };
        devShells.default = pkgs.mkShell {
          inputsFrom = [ self.packages.${system}.myapp-env.env ];
        };
      });
}
```

`pyproject.toml`:
```toml
[tool.poetry]
name = "app"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.scripts]
testing = "app:main"

[tool.poetry.dependencies]
python = "^3.11"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

`poetry.lock`:
```toml
# This file is automatically @generated by Poetry 1.6.1 and should not be changed by hand.
package = []

[metadata]
lock-version = "2.0"
python-versions = "^3.11"
content-hash = "81b2fa642d7f2d1219cf80112ace12d689d053d81be7f7addb98144d56fc0fb2"
```

The result is that changing the main function in `app/__init__.py` will change the behaviour of the `testing` script (within the devshell defined in the flake).

If this `app` package is moved to a `src` folder, and the following changes are applied to the `flake.nix` and `pyproject.toml` files, this behaviour is lost, and only recompiling the project will apply the changes. The only changes are changing the `editablePackageSources.app` attribute from `./.` to `./src` in the `flake.nix` file, and adding `packages = [{include="app", from="src}]` to the `[tool.poetry]` field of the `pyproject.toml` file:

`default.nix`/`shell.nix`/`flake.nix`:
```nix
{
  description = "Application packaged using poetry2nix";

  inputs = {
    flake-utils.url = "github:numtide/flake-utils";
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable-small";
    poetry2nix = {
      url = "github:nix-community/poetry2nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = { self, nixpkgs, flake-utils, poetry2nix }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = nixpkgs.legacyPackages.${system};
        inherit (poetry2nix.lib.mkPoetry2Nix { inherit pkgs; }) mkPoetryEnv;

      in
      {
        packages.myapp-env = mkPoetryEnv {
          projectDir = self;
          editablePackageSources.app = ./src;
        };
        devShells.default = pkgs.mkShell {
          inputsFrom = [ self.packages.${system}.myapp-env.env ];
        };
      });
}
```

`pyproject.toml`:
```toml
[tool.poetry]
name = "app"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
license = "MIT"
readme = "README.md"
packages = [
    {include = "app", from = "src"},
]

[tool.poetry.scripts]
testing = "app:main"

[tool.poetry.dependencies]
python = "^3.11"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

`poetry.lock`:
```toml
# This file is automatically @generated by Poetry 1.6.1 and should not be changed by hand.
package = []

[metadata]
lock-version = "2.0"
python-versions = "^3.11"
content-hash = "81b2fa642d7f2d1219cf80112ace12d689d053d81be7f7addb98144d56fc0fb2"
```
