### ISSUE TITLE
`apache-flink = "^1.19.1"` does not work on MacOS

### ISSUE THREAD

**Issue by usmcamp0811** [nix-community/poetry2nix#1757]
### Describe the issue

I have a [Nix Flink package](https://gitlab.com/usmcamp0811/dotfiles/-/tree/nixos/packages/example-flink-job?ref_type=heads) that works 100% correctly on all things Linux. One of its dependencies is a Python environment with `apache-flink`. When my buddy who has a Mac runs the package he gets the attached [error.](https://github.com/user-attachments/files/16461480/error.txt). 

Skimming through the error it looks like `pyarrow` might be the problem which I believe is a dep of `apache-beam`. But any way I pulled out the Python environment and made a colorful package to attempt to isolate the problem. 

```bash
# has `apache-flink` no work on Mac
nix run gitlab:usmcamp0811/dotfiles/5fb41f9a60c833656996e4853ebfca3d4d17fc10#macossucksballs

# no `apache-flink` works on Mac
nix run gitlab:usmcamp0811/dotfiles/1c47084208caa0a31ba472e5941a125831ff24e1#macossucksballs
```
My buddy with the Mac can run the second but not the first. He gets the same error as in the attached error trace. 

### Additional context

`default.nix`/`shell.nix`/`flake.nix`:
```nix
{ lib, inputs, pkgs, ... }:
let
  src = ./.;
  pypkgs-build-requirements = {
    avro = [ "setuptools" ];
    avro-python3 =
      [ "setuptools" "python-snappy" "zstandard" "isort" "pycodestyle" ];
    apache-flink = [ "setuptools" "pyarrow" ];
    mocker = [ "setuptools" ];
    apache-flink-libraries = [ "setuptools" ];
  };

  p2n-overrides = pkgs.poetry2nix.defaultPoetryOverrides.extend (self: super:
    builtins.mapAttrs (package: build-requirements:
      super."${package}".overridePythonAttrs (oldAttrs: {
        buildInputs = (oldAttrs.buildInputs or [ ])
          ++ (builtins.map (req: super."${req}") build-requirements);
      })) pypkgs-build-requirements);
  python-env = pkgs.poetry2nix.mkPoetryEnv {
    projectDir = src;
    python = pkgs.python311;
    overrides = p2n-overrides;
    preferWheels = true; # Prefer wheels to speed up the build process
  };
in python-env
```

`pyproject.toml`:
```toml
[tool.poetry]
name = "example-flink-job"
version = "0.1.0"
description = ""
authors = ["Matt Camp <matt@aicampground.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
setuptools = "^65.5.0"  # Add this line
pyarrow = "^17.0.0"

[tool.poetry.group.dev.dependencies]
pytest-mock = "^3.14.0"
pytest = "^8.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

```
