### ISSUE TITLE
Broken Sphinx Book Theme

### ISSUE THREAD

**Issue by HaoZeke** [nix-community/poetry2nix#179]
# Bug Report
Hi.

## Description

The error in question is:
```bash
[Errno 13] Permission denied: '/nix/store/i53cgji8hk616aiqgrxzd33vjm21ja5a-python3-3.8.5-env/lib/python3.8/site-packages/sphinx_book_theme/static/sphinx-book-theme.css')
```

The corresponding `pyproject.toml` is:

```toml
[tool.poetry]
name = "symengine.github.io"
version = "0.1.0"
description = "Symengine Doxygen-Sphinx setup"
authors = ["Rohit Goswami <rgoswami@ieee.org>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
exhale = "^0.2.3"
breathe = "^4.20.0"
nbsphinx = "^0.7.1"
myst-nb = "^0.10.1"
sphinx-book-theme = "^0.0.36"
coverxygen = "^1.5.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```

The error arises from a standard `sphinx-build` command run with the standard `config.py` line, namely `html_theme = 'sphinx_book_theme'`.

### Reproducibility

The full log can be found [here on Travis](https://travis-ci.com/github/symengine/symengine.github.io/builds/186105401) corresponding to [the Symengine documentation project (commit linked)](https://github.com/symengine/symengine.github.io/tree/96bc769f2239ff8e1495b24284405226aede6013).

## Thoughts
It would appear that this directory needs to be writable, is there a way to extend the `editablePackageSources` scope to these use-cases?
