### ISSUE TITLE
Cannot build Python extras with dash in name "-"

### ISSUE THREAD

**Issue by sireliah** [nix-community/poetry2nix#309]
Hi everyone! I've found a pretty specific issue with adding a Python extras which contains a dash symbol.

```
poetry add boto3-stubs[cognito-idp] 
```
## The error:
```bash
$ nix build
error: value is null while a list was expected, at /nix/store/sccc9mb8brnc6n2xmnac8hz67sj5qpcm-nixpkgs-21.05pre278688.c0e88185200/nixpkgs/pkgs/development/tools/poetry2nix/poetry2nix/pep508.nix:135:19
(use '--show-trace' to show detailed location information)
```
## The cause
[The regex](https://github.com/nix-community/poetry2nix/blob/master/pep508.nix#L132) that is parsing the submodules seems to be missing the dash.

## The possible fix
Adding the dash to the regex fixes the issue.
```
mVal = ''[a-zA-Z0-9\'"_\. \-]+'';
```

## Test setup:

nix (Nix) 2.3.1
channel: https://nixos.org/channels/nixpkgs-unstable
Poetry version: 1.1.6
poetry2nix version: master

```toml
# pyproject.toml
[tool.poetry]
name = "nix-poetry-test"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
boto3-stubs = {extras = ["cognito-idp"], version = "^1.17.77"}

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

```nix
# default.nix
{ pkgs ? import <nixpkgs> {} }:

let
  poetry2nix = pkgs.poetry2nix;
  python3 = pkgs.python3;
in
poetry2nix.mkPoetryApplication {
  python = python3;
  projectDir = ./.;
}
```

If you're fine with that fix, I'll open a PR. Thanks for the attention!
