### ISSUE TITLE
fails to fetch wheel, "tar: This does not look like a tar archive"

### ISSUE THREAD

**Issue by enolan** [nix-community/poetry2nix#339]
Wheels are [defined as ZIP files](https://www.python.org/dev/peps/pep-0491/#abstract) files. But it's for some reason trying and failing to treat it as a tar archive.

Example `pyproject.toml`
```toml
[tool.poetry]
name = "wheeltest"
version = "0.1.0"
description = ""
authors = ["Echo Nolan <echo@echonolan.net>"]

[tool.poetry.dependencies]
python = "^3.8"
torch = {url = "https://download.pytorch.org/whl/cu111/torch-1.9.0%2Bcu111-cp38-cp38-linux_x86_64.whl"}

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

`poetry.lock` is [here](https://gist.github.com/enolan/5eba4389ae8c742902c9baea8a38b54e).

And `shell.nix`:
```
{ pkgs ? import <nixpkgs> {}}:
let
  env = (import <p2n>).mkPoetryEnv {
    python = pkgs.python38;
    projectDir = ./.;
  };
in
env.env
```

I'm running `nix-shell --show-trace -I p2n=https://github.com/nix-community/poetry2nix/archive/136f166f3b90dc1e975b991ff52122450fe2aa1f.zip` so it should be the latest version from this repo.

Exact error:
```
enolan@chonk ~/j/wheeltest> nix-shell --show-trace -I p2n=https://github.com/nix-community/poetry2nix/archive/136f166f3b90dc1e975b991ff52122450fe2aa1f.zip
unpacking 'https://github.com/nix-community/poetry2nix/archive/136f166f3b90dc1e975b991ff52122450fe2aa1f.zip'...
tar: This does not look like a tar archive
tar: Skipping to next header
tar: Exiting with failure status due to previous errors
error: while evaluating anonymous function at /home/enolan/junk/wheeltest/shell.nix:1:1, called from undefined position:
program 'tar' failed with exit code 2
```
