### ISSUE TITLE
Python 2.7 support

### ISSUE THREAD

**Issue by jameysharp** [nix-community/poetry2nix#560]
### Describe the issue

I'm trying to package a Python 2.7-only project using a Nix expression like:

```nix
pkgs.poetry2nix.mkPoetryApplication {
  python = pkgs.python27;
  projectDir = ./.;
}
```

This fails because the 2.7-specific dependencies for `poetry-core` aren't installed. The first time that Pip tries to invoke the poetry-core backend, it raises a `BackendUnavailable` exception. (There are no further details in the exception, which made debugging a pain, but that's not a Nix problem.)

If you run Python in `nix-shell ./default.nix` from the project directory, you can see the underlying error:

```
>>> import poetry.core.masonry.api
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nix/store/m8v28yikv9phlswvdihsklksd95xvr2m-python2.7-poetry-core-1.0.7/lib/python2.7/site-packages/poetry/core/__init__.py", line 8, in <module>
    from pathlib2 import Path
ImportError: No module named pathlib2
```

### Additional context

I've set up a minimal example at <https://github.com/jameysharp/poetry2nix-py2>. The `broken/pyproject.toml` is trivial:

```toml
[tool.poetry]
name = "broken"
version = "0.1.0"
description = ""
authors = ["Jamey Sharp <jamey@minilop.net>"]
license = "MIT"

[tool.poetry.scripts]
hello = 'broken:run'

[tool.poetry.dependencies]
python = "^2.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

The smallest successful workaround I've found is to add `poetry-core`'s dependencies as dev-dependencies of my project:

```
--- broken/pyproject.toml	2022-02-24 21:24:27.532546658 -0800
+++ working/pyproject.toml	2022-02-24 21:24:27.531546654 -0800
@@ -14,2 +14,5 @@
 [tool.poetry.dev-dependencies]
+importlib-metadata = {version = "^1.7.0", python = "~2.7 || >=3.5, <3.8"}
+enum34 = {version = "^1.1.10", python = "~2.7"}
+functools32 = {version = "^3.2.3-2", python = "~2.7"}
 
```

But that doesn't seem like a _good_ solution. I'm not even entirely sure why it works.

I thought it was also necessary to downgrade `poetry-core` to 1.0.2, which looked to me like the last version which supported Python 2. However, this repo demonstrates that 1.0.7 seems to work fine. :shrug:
