### ISSUE TITLE
poetry-dynamic-versioning?

### ISSUE THREAD

**Issue by yajo** [nix-community/poetry2nix#566]
### Describe the issue

When running `nix build` of a flake with poetry2nix, I get this error:

```
error: unsupported build system requirement poetry-dynamic-versioning
```

### Additional context

I guess it comes from this part of the `pyproject.toml` file:
```toml
[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning"]
build-backend = "poetry.core.masonry.api"
```

https://github.com/mtkennerly/poetry-dynamic-versioning is a poetry plugin that gets injected and automatically sets the program version based on some rules and the matching vcs tag.
