### ISSUE TITLE
How to set up build system override in `mkPoetryEnv`?

### ISSUE THREAD

**Issue by l0b0** [nix-community/poetry2nix#655]
### Describe the issue

As a relative Nix newbie it's not obvious how to create a new override to emulate `addBuildSystem` (I'm trying to avoid changing `build-systems.json` itself, if that makes sense). For example, jsonschema 4.6.0 seems to require hatchling, but the override

```
jsonschema = super.jsonschema.overridePythonAttrs (
  old: {
    nativeBuildInputs = (old.nativeBuildInputs or [ ]) ++ [
      self.hatchling
      self.hatch-vcs
    ];
  }
);
```

just results in a different error:

> ERROR: Could not find a version that satisfies the requirement pluggy>=1.0.0; python_version > "3" (from hatchling) (from versions: none)

Does this error require a different override, or did I do something wrong with my hatchling override?

**Comment by sigprof** [comment]
The above override actually works for me if I use a recent nixpkgs snapshot that has usable `hatchling` and `hatch-vcs` Python packages.

Another option is to add the required modules to `pyproject.toml` (e.g., to the `[tool.poetry.dev-dependencies]` section), then poetry2nix would use the module versions specified there instead of taking whatever is in nixpkgs (and would also pick up any dependencies like that `pluggy` module). However, you may run into version conflicts with other modules; e.g., this is what I ended up with at the moment:
```toml
# These dependencies are required by the jsonschema >= 4.6.0 build system, but
# are not detected automatically; they are also not present in the used Nixpkgs
# snapshot, so need to be obtained through Poetry.
hatchling = "*"
hatch-vcs = "*"

# The `pytest` module in the used Nixpkgs snapshot has an upper bound on the
# `pluggy` dependency, which conflicts with the dependency of the `hatchling`
# module; upgrading the `pytest` module fixes the conflict.
pytest = "*"

# Building the `tomli` module, which is in the dependency tree of `hatchling`,
# requires a newer `flit` module than found in the used Nixpkgs snapshot.
flit = "*"
```

I suppose that the PR to add the override for `jsonschema` would need to use `if (lib.versionAtLeast super.jsonschema.version "4.6.0")` to keep older module versions working as before.
