### ISSUE TITLE
How to use plugin system, trying to use keyrings-google-artifactregistry-auth

### ISSUE THREAD

**Issue by DylanRJohnston-FZ** [nix-community/poetry2nix#672]
### Describe the issue
I'm trying to make use of poetry2nix where we have a private artifact repository on google cloud. Normally the keyring plugin keyrings.google-artifactregistry-auth allows Poetry to authenticate against the private repository. However it's unclear how to achieve this with poetry2nix.

### Additional context
I initially tried using an overlay to put `keyrings-google-artifactregistry-auth` in the `propogatedBuildInputs` but quickly realised this doesn't work because Poetry doesn't use the typical nixpkgs callPackage convention and instead uses poetry itself to manage its own dependencies.

I could potentially achieve this by overriding the pyproject and poetrylock files to include the google keyring plugin.

```
, pyproject ? projectDir + "/pyproject.toml"
, poetrylock ? projectDir + "/poetry.lock"
```

However when searching the repository, I found an undocumented `withPlugins` method that I was hoping you'd help me figure out how to use.

**Comment by DylanRJohnston-FZ** [comment]
poetry.toml
```toml
[repositories]
[repositories.redacted]
url = "https://redacted.pkg.dev/redacted/python"
```
pyproject.toml
```toml
[[tool.poetry.source]]
name = "redacted"
secondary = true
url = "https://redacted.pkg.dev/redacted/python/simple/"
```
