### ISSUE TITLE
Recent poetry build fails with `drv` is `null`

### ISSUE THREAD

**Issue by johnrichardrinehart** [nix-community/poetry2nix#697]
### Describe the issue

I just copied `pyproject.toml` and `poetry.lock` from the tip of https://github.com/python-poetry/poetry and used `poetry2nix.mkPoetryApplication` to try to package `poetry` like is done in `nixpkgs` (I also tried modifying these files and the source JSON in `nixpkgs` but got the same result as below). But, I find that for some reason the evaluation fails because the `drv` (some derivation) is `null`. I'm not sure how to make it un-`null` but I will accept any support/change to facilitate packaging one of the most recent commits of `python-poetry/poetry`.

```bash
$ nix build github:johnrichardrinehart/poetry-flake
error: value is null while a set was expected

       at /nix/store/p3bvy3abha8dihrczhsfmcvp3a87dwd2-source/pkgs/development/tools/poetry2nix/poetry2nix/overrides/default.nix:41:9:

           40|       else
           41|         drv.overridePythonAttrs (
             |         ^
           42|           old:
(use '--show-trace' to show detailed location information)
```

### Additional context

- `default.nix`/`shell.nix`/`flake.nix`

All code is visible at https://github.com/johnrichardrinehart/poetry-flake . It's pretty simple. The `pyproject.toml` and `poetry.lock` were ripped directly from `python-poetry/poetry@main` (those files haven't been touched since [`7bb0a8762d42f6400cc677ee85c744033d5490d0`](https://github.com/python-poetry/poetry/tree/7bb0a8762d42f6400cc677ee85c744033d5490d0).
```nix
{
  description = "A very basic flake";

  outputs = { self, nixpkgs }: 
  let
    system = "x86_64-linux";
    poetry2nix = nixpkgs.legacyPackages.${system}.poetry2nix;
  in
  {
    packages.x86_64-linux.poetry = poetry2nix.mkPoetryApplication {
      projectDir = ./.;
    };

    defaultPackage.x86_64-linux = self.packages.x86_64-linux.poetry;
  };
}
```

- `pyproject.toml`
```toml
[tool.poetry]
name = "poetry"
version = "1.2.0rc1.dev0"
description = "Python dependency management and packaging made easy."
authors = [
    "Sébastien Eustace <sebastien@eustace.io>",
]
maintainers = [
    "Arun Babu Neelicattu <arun.neelicattu@gmail.com>",
    "Bjorn Neergaard <bjorn@neersighted.com>",
    "Branch Vincent <branchevincent@gmail.com>",
    "Bryce Drennan <github@accounts.brycedrennan.com>",
    "Daniel Eades <danieleades@hotmail.com>",
    "Randy Döring <radoering.poetry@gmail.com>",
    "Steph Samson <hello@stephsamson.com>",
    "finswimmer <finswimmer77@gmail.com>",
]
license = "MIT"

readme = "README.md"

packages = [
    { include = "poetry", from = "src" }
]
include = [
    { path = "tests", format = "sdist" }
]

homepage = "https://python-poetry.org/"
repository = "https://github.com/python-poetry/poetry"
documentation = "https://python-poetry.org/docs"

keywords = ["packaging", "dependency", "poetry"]

classifiers = [
    "Topic :: Software Development :: Build Tools",
    "Topic :: Software Development :: Libraries :: Python Modules"
]

[tool.poetry.build]
generate-setup-file = false

# Requirements
[tool.poetry.dependencies]
python = "^3.7"

poetry-core = "^1.1.0b3"
poetry-plugin-export = "^1.0.6"
cachecontrol = { version = "^0.12.9", extras = ["filecache"] }
cachy = "^0.3.0"
cleo = "^1.0.0a5"
crashtest = "^0.3.0"
html5lib = "^1.0"
importlib-metadata = { version = "^4.4", python = "<3.10" }
# keyring uses calver, so version is unclamped
keyring = ">=21.2.0"
# packaging uses calver, so version is unclamped
packaging = ">=20.4"
pexpect = "^4.7.0"
pkginfo = "^1.5"
platformdirs = "^2.5.2"
requests = "^2.18"
requests-toolbelt = "^0.9.1"
shellingham = "^1.5"
# exclude 0.11.2 and 0.11.3 due to https://github.com/sdispater/tomlkit/issues/225
tomlkit = ">=0.11.1,<1.0.0,!=0.11.2,!=0.11.3"
# exclude 20.4.5 - 20.4.6 due to https://github.com/pypa/pip/issues/9953
virtualenv = "(>=20.4.3,<20.4.5 || >=20.4.7)"
xattr = { version = "^0.9.7", markers = "sys_platform == 'darwin'" }
urllib3 = "^1.26.0"
dulwich = "^0.20.44"

[tool.poetry.dev-dependencies]
tox = "^3.18"
pytest = "^7.1"
pytest-cov = "^3.0"
pytest-mock = "^3.5"
pytest-randomly = "^3.10"
pytest-sugar = "^0.9"
pytest-xdist = { version = "^2.5", extras = ["psutil"] }
pre-commit = "^2.6"
deepdiff = "^5.0"
httpretty = "^1.0"
typing-extensions = { version = "^4.0.0", python = "<3.8" }
zipp = { version = "^3.4", python = "<3.8" }
flatdict = "^4.0.1"
mypy = ">=0.960"
types-html5lib = ">=1.1.7"
types-jsonschema = ">=4.4.4"
types-requests = ">=2.27.11"

[tool.poetry.scripts]
poetry = "poetry.console.application:main"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.isort]
py_version = 37
profile = "black"
force_single_line = true
combine_as_imports = true
lines_between_types = 1
lines_after_imports = 2
src_paths = ["src", "tests"]
extend_skip = ["setup.py"]
known_third_party = ["poetry.core"]


[tool.black]
target-version = ['py37']
preview = true
force-exclude = '''
.*/setup\.py$
'''


[tool.mypy]
files = "src"
mypy_path = "src"
namespace_packages = true
explicit_package_bases = true
show_error_codes = true
strict = true
enable_error_code = [
    "ignore-without-code",
    "redundant-expr",
    "truthy-bool",
]

# use of importlib-metadata backport at python3.7 makes it impossible to
# satisfy mypy without some ignores: but we get a different set of ignores at
# different python versions.
#
# <https://github.com/python/mypy/issues/8823>, meanwhile suppress that
# warning.
[[tool.mypy.overrides]]
module = [
  'poetry.console.commands.self.show.plugins',
  'poetry.installation.executor',
  'poetry.mixology.version_solver',
  'poetry.plugins.plugin_manager',
  'poetry.repositories.installed_repository',
  'poetry.utils.env',
]
warn_unused_ignores = false

[[tool.mypy.overrides]]
module = [
  'cachecontrol.*',
  'cachy.*',
  'cleo.*',
  'crashtest.*',
  'pexpect.*',
  'pkginfo.*',
  'requests_toolbelt.*',
  'shellingham.*',
  'virtualenv.*',
  'xattr.*',
]
ignore_missing_imports = true

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "if TYPE_CHECKING:"
]
```

- `poetry.lock`
**Omitted because including it inline exceeds GitHub's maximum body length (65536 characters). However, contents are visible at https://github.com/johnrichardrinehart/poetry-flake/blob/main/poetry.lock.**
