### ISSUE TITLE
Error in while executing `pipBuildPhase` due to `poetry2nix`'s pip missing dependency

### ISSUE THREAD

**Issue by Danielhp95** [nix-community/poetry2nix#705]
I am relatively new to python development on nix, so I apologize if my analysis is wrong!

I am trying to build a python environment by using most of the default functionality. Most importantly, I am trying to get `torch` with cuda working properly.

Here's my default.nix
```nix
with import <nixpkgs> {};
let
  myEnv = poetry2nix.mkPoetryEnv {
    projectDir =  ./.;
    python = python3;   # This is default
  };
in myEnv.env
```

Here's the contents of my `pyproject.toml`
```toml
[tool.poetry]
name = "stable-diffusion"
version = "0.1.0"
description = ""
authors = ["Imagine your text"]

[tool.poetry.dependencies]
python = "^3.8"
cython = "^0.29.30"
torch = "^1.11.0"
torchvision = "^0.12.0"
numpy = "^1.19.2"
albumentations = "^0.4.3"
opencv-python = "*"
imageio = "^2.9.0"
imageio-ffmpeg = "^0.4.2"
pytorch-lightning = "^1.4.2"
omegaconf = "^2.1.1"
test-tube = "^0.7.5"
streamlit = "^0.73"
einops = "^0.3.0"
torch-fidelity = "^0.3.0"
transformers = "^4.19.2"
torchmetrics = "^0.6.0"
kornia = "^0.6"
taming-transformers = { git = "https://github.com/CompVis/taming-transformers.git"}
clip = { git = "https://github.com/openai/CLIP.git", branch="main"}

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

This is the contents of the `poetry.lock` is around  2800 of dependencies, so I  am not pasting it unless necessary.

When running `nix-shell default.nix`, `poetry2nix` tries to do its thing but it breaks on the following error:

```
Sourcing python-remove-tests-dir-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh
Sourcing pip-build-hook
Using pipBuildPhase
Using pipShellHook
Sourcing pip-install-hook
Using pipInstallPhase
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
Sourcing python-namespaces-hook
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/rlbcsn5pd2fqdxfqfhgs6zk4kvn0qjpp-jsonschema-4.15.0.tar.gz
source root is jsonschema-4.15.0
setting SOURCE_DATE_EPOCH to timestamp 1580601600 of file jsonschema-4.15.0/tox.ini
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
Removing path dependencies
Finished removing path dependencies
Removing git dependencies
Finished removing git dependencies
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
no configure script, doing nothing
@nix { "action": "setPhase", "phase": "buildPhase" }
building
Executing pipBuildPhase
Creating a wheel...
[33mWARNING: The directory '/homeless-shelter/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.[0m[33m
[0mProcessing /build/jsonschema-4.15.0
  Running command Preparing metadata (pyproject.toml)
  Traceback (most recent call last):
    File "/nix/store/x9wcjj4xmc7nrk41ll63i56qc1nl0shh-python3.9-pip-22.1.2/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 156, in prepare_metadata_for_build_wheel
      hook = backend.prepare_metadata_for_build_wheel
  AttributeError: module 'hatchling.build' has no attribute 'prepare_metadata_for_build_wheel'

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/nix/store/x9wcjj4xmc7nrk41ll63i56qc1nl0shh-python3.9-pip-22.1.2/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
      main()
    File "/nix/store/x9wcjj4xmc7nrk41ll63i56qc1nl0shh-python3.9-pip-22.1.2/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/nix/store/x9wcjj4xmc7nrk41ll63i56qc1nl0shh-python3.9-pip-22.1.2/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 160, in prepare_metadata_for_build_wheel
      whl_basename = backend.build_wheel(metadata_directory, config_settings)
    File "/nix/store/cqbi7xykq0pcb3hf2aab2h1gq892431w-python3.9-hatchling-0.25.0/lib/python3.9/site-packages/hatchling/build.py", line 41, in build_wheel
      return os.path.basename(next(builder.build(wheel_directory, ['standard'])))
    File "/nix/store/cqbi7xykq0pcb3hf2aab2h1gq892431w-python3.9-hatchling-0.25.0/lib/python3.9/site-packages/hatchling/builders/plugin/interface.py", line 77, in build
      self.metadata.core.validate_fields()
    File "/nix/store/cqbi7xykq0pcb3hf2aab2h1gq892431w-python3.9-hatchling-0.25.0/lib/python3.9/site-packages/hatchling/metadata/core.py", line 103, in core
      metadata_hooks = self.hatch.metadata.hooks
    File "/nix/store/cqbi7xykq0pcb3hf2aab2h1gq892431w-python3.9-hatchling-0.25.0/lib/python3.9/site-packages/hatchling/metadata/core.py", line 1311, in hooks
      raise UnknownPluginError('Unknown metadata hook: {}'.format(hook_name))
  hatchling.plugin.exceptions.UnknownPluginError: Unknown metadata hook: fancy-pypi-readme
  [1;31merror[0m: [1msubprocess-exited-with-error[0m
  
  [31m×[0m [32mPreparing metadata [0m[1;32m([0m[32mpyproject.toml[0m[1;32m)[0m did not run successfully.
  [31m│[0m exit code: [1;36m1[0m
  [31m╰─>[0m See above for output.
  [1;35mnote[0m: This error originates from a subprocess, and is likely not a problem with pip.
  [1;35mfull command[0m: [34m/nix/store/xpwwghl72bb7f48m51amvqiv1l25pa01-python3-3.9.13/bin/python3.9 /nix/store/x9wcjj4xmc7nrk41ll63i56qc1nl0shh-python3.9-pip-22.1.2/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /build/tmpenvx2inq[0m
  cwd: /build/jsonschema-4.15.0
  Preparing metadata (pyproject.toml) ... error
error: metadata-generation-failed

Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

This points at two errors:

1. `AttributeError: module 'hatchling.build' has no attribute 'prepare_metadata_for_build_wheel'`
2. `hatchling.plugin.exceptions.UnknownPluginError: Unknown metadata hook: fancy-pypi-readme`

I am not sure about (1), but (2) seems to indicate that [hatch](https://hatch.pypa.io/latest/) is being used during `pipBuildPhase` and it is missing the plugin [`fancy-pypi-readme`](https://github.com/hynek/hatch-fancy-pypi-readme).

Is there anyway that we can add [`fancy-pypi-readme`](https://github.com/hynek/hatch-fancy-pypi-readme) to the python environment used by `poetry2nix` to build the target python environment? As per #176 we can't just change the `python` attribute that goes into `poetry2nix.mkPoetryEnv`.

Any suggestions?
