### ISSUE TITLE
Correctly parse poetry source indexes with basic auth creds

### ISSUE THREAD

**Issue by jperras** [nix-community/poetry2nix#846]
### Describe the issue

If one has a `pyproject.toml` with a custom source that had basic auth credentials in the URL, e.g.

```toml
[[tool.poetry.source]]
name = "private_source"
url = "https://username:password@pypi.example.com/pypi"
```

The `fetch_from_legacy.py` script would fail to parse, erroneously splitting on the `:` thinking that whatever came after it was a numeric port identifier, such as in `https://example.com:8080`.

### Additional Details

While embedding authentication credentials in an index URL that is then committed to a `pyproject.toml` is not what one would consider best practice (there are several alternative approaches that keep credentials out of the `pyproject.toml` file), it _is_ supported by the direct usage of Poetry, and those legacy projects should still be able to utilize `poetry2nix`.
