### ISSUE TITLE
Cryptography 39.0.0 sha256 error

### ISSUE THREAD

**Issue by Industrial** [nix-community/poetry2nix#978]
### Describe the issue
```
error: hash mismatch in fixed-output derivation '/nix/store/cj316zca0b26dknjvrcwwvr1dy6z2g3a-cryptography-39.0.0-vendor.tar.gz.drv':
         specified: sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
            got:    sha256-clorC0NtGukpE3DnZ84MSdGhJN+qC89DZPITZFuL01Q=
```

### Additional context
Using https://github.com/nix-community/poetry2nix/blob/master/overrides/default.nix#L412 I made an override like so:

`default.nix`/`shell.nix`/`flake.nix`:
```nix
          cryptography = super.cryptography.overridePythonAttrs (
            old: {
              cargoDeps =
                pkgs.rustPlatform.fetchCargoTarball {
                  src = old.src;
                  sourceRoot = "${old.pname}-${old.version}/src/rust";
                  name = "${old.pname}-${old.version}";
                  sha256 = "sha256-clorC0NtGukpE3DnZ84MSdGhJN+qC89DZPITZFuL01Q=";
                };
            }
          );
```

`pyproject.toml`:
```toml
[tool.poetry]
name = "ft_userdata"
version = "0.1.0"
description = ""
authors = ["Tom Wieland <tom.wieland@gmail.com>"]
readme = "README.md"
packages = []

[tool.poetry.dependencies]
freqtrade = "^2023.1"
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pyright]
include = ["user_data"]
exclude = [
  "**/node_modules",
  "**/__pycache__",
]
ignore = []
defineConstant = {}
stubPath = "user_data/stubs"
venv = ".venv"

reportMissingImports = true
reportMissingTypeStubs = false

pythonVersion = "3.10"
pythonPlatform = "Linux"

executionEnvironments = [
  { root = "user_data" }
]
```

Didn't include poetry.lock due to body size limit
`poetry.lock`:
```toml
```
